### ISSUE TITLE
Relicense as MPL 2.0

### ISSUE THREAD

**Issue by aepsil0n** [aepsil0n/acacia#53]
Similar to how I proceeded with carboxyl, this library will be available under LGPL 3.0+, too. I just have to copy & paste the license stuff.

**Comment by Moredread** [comment]
Will you still license the project under the LGPL after the relicensing of carboxyl, or will you change the license to the MPL?

**Comment by aepsil0n** [comment]
Uhm, no I think for me personally this discussion is over now and it's MPL for all the things ^^

Never revisited this top for this library in particular. Would you mind the change?

**Comment by Moredread** [comment]
No, I'm completely against it, sue me!

**Comment by Moredread** [comment]
JK XD Sure, I'll make a PR.

**Comment by Moredread** [comment]
See #91
