### ISSUE TITLE
Version bump?

### ISSUE THREAD

**Issue by Moredread** [aepsil0n/acacia#83]
with incompatibilities with nalgebra < 0.9 due to name changes, should there be a minor version bump for acacia?

**Comment by aepsil0n** [comment]
Yes. `nalgebra` is an integral part of the partition implementations without which `acacia` is pretty useless.

**Comment by Moredread** [comment]
Can you push a new release? I there aren't much changes from the last crates.io version, but I need it due to this change for publishing dagon.

**Comment by Moredread** [comment]
Closed with release of acicia 0.1.2
