### ISSUE TITLE
Opinion on repartitioning

### ISSUE THREAD

**Issue by Moredread** [aepsil0n/acacia#86]
In-place updates of the tree structure when e.g. only some of the data has been changed, can be much faster (according to the GADGET paper atleast, haven't done benchmarks myself, but it seems plausible). The same should be true, when only some data is removed or later inserted.

Do you think that the current framework could be adapted to support such mutable operations?

**Comment by aepsil0n** [comment]
Sure, why not? I wouldn't mind integrating that into the API. Although I am not quite sure how amenable the current data structures are to mutability.

Personally I'd first try to share ownership of the unchanged branches between the old and new tree. But these would be different kinds of trees then.

**Comment by aepsil0n** [comment]
Closing this in favour of #35. It does cover the same thing, as far as I understand.
